services:
    db:
        image: postgres:17.4
        ports:
            - 127.0.0.1:5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: localdb
            POSTGRES_DB: dieselversioning
        volumes:
            - ./docker/postgres:/var/lib/postgresql/data
